# Generated by Django 3.1.5 on 2021-01-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0002_auto_20210107_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
