# Generated by Django 3.1.5 on 2021-01-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0003_auto_20210107_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='image_src',
        ),
        migrations.AddField(
            model_name='toy',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
