# Generated by Django 3.1.5 on 2021-01-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0004_auto_20210107_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
